version: '3.8'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap-server
    hostname: ldap-service
    environment:
      LDAP_ADMIN_PASSWORD: password
      LDAP_BASE_DN: cn=admin,dc=example,dc=org
    ports:
      - 389:389
    volumes:
      - ./ldap-data:/var/lib/ldap
      - ./ldap-config:/etc/ldap/slapd.d
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin-service
    hostname: phpldapadmin-service
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-host
    links:
      - openldap:ldap-host
    ports:
      - 6443:443
    depends_on:
      - openldap
  apache-php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./public-html:/var/www/html
      - ./config-php:/usr/local/etc/php
      - ./config-apache:/etc/apache2
    depends_on:
      - openldap
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    ports:
      - 33060:3306
    volumes:
      - .mysql_data:/var/lib/mysql:rw
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
volumes:
  src: {}
  config-php: {}
  config-apache: {}
  .mysql_data: {}
  ldap-data: {}
  ldap-config: {}
